"""Cognition adapters: rules, mock, cache, replay, the HTTP provider, and the service."""

from adlife.adapters.cognition.cache import (
    CACHE_KEY_VERSION,
    CacheMiss,
    CognitionCache,
    CorruptCacheRecord,
)
from adlife.adapters.cognition.mock import (
    MOCK_FIXTURE_COUNT,
    MOCK_MODEL_ID,
    MockCognitionProvider,
)
from adlife.adapters.cognition.openai_compatible import (
    ADLIFE_API_KEY_VARIABLE,
    DEFAULT_LOCAL_BASE_URL,
    HIDDEN_API_KEY_PROMPT,
    LOCAL_API_KEY_PLACEHOLDER,
    InsecureProviderUrl,
    InvalidProviderResponse,
    MissingApiKey,
    OpenAICompatibleProvider,
    ProviderCall,
    ProviderCallError,
    ProviderConfigurationError,
    ProviderHttpError,
    ProviderRateLimited,
    ProviderTimeout,
    ProviderUnavailable,
    resolve_api_key,
)
from adlife.adapters.cognition.prompts import (
    BEGIN_SIMULATION_DATA,
    END_SIMULATION_DATA,
    SYNTHETIC_DATA_DISCLOSURE,
    SYSTEM_INSTRUCTION,
    build_messages,
    build_repair_messages,
    cognition_json_schema,
    prompt_template_sha256,
)
from adlife.adapters.cognition.replay import ReplayCognitionProvider
from adlife.adapters.cognition.rules import (
    RULE_MODEL_ID,
    MismatchedRuleResponse,
    RuleCognitionInputs,
    RuleCognitionProvider,
    UnknownCognitionRequest,
    UnrepresentableRuleResult,
    rule_cognition_result,
    rule_emotion,
)
from adlife.adapters.cognition.service import (
    MAX_CONCURRENT_PROVIDER_CALLS,
    MAX_PROVIDER_ATTEMPTS,
    CognitionBudget,
    CognitionResolution,
    CognitionService,
    DuplicateCognitionRequest,
)

__all__ = [
    "ADLIFE_API_KEY_VARIABLE",
    "BEGIN_SIMULATION_DATA",
    "CACHE_KEY_VERSION",
    "DEFAULT_LOCAL_BASE_URL",
    "END_SIMULATION_DATA",
    "HIDDEN_API_KEY_PROMPT",
    "LOCAL_API_KEY_PLACEHOLDER",
    "MAX_CONCURRENT_PROVIDER_CALLS",
    "MAX_PROVIDER_ATTEMPTS",
    "MOCK_FIXTURE_COUNT",
    "MOCK_MODEL_ID",
    "RULE_MODEL_ID",
    "SYNTHETIC_DATA_DISCLOSURE",
    "SYSTEM_INSTRUCTION",
    "CacheMiss",
    "CognitionBudget",
    "CognitionCache",
    "CognitionResolution",
    "CognitionService",
    "CorruptCacheRecord",
    "DuplicateCognitionRequest",
    "InsecureProviderUrl",
    "InvalidProviderResponse",
    "MismatchedRuleResponse",
    "MissingApiKey",
    "MockCognitionProvider",
    "OpenAICompatibleProvider",
    "ProviderCall",
    "ProviderCallError",
    "ProviderConfigurationError",
    "ProviderHttpError",
    "ProviderRateLimited",
    "ProviderTimeout",
    "ProviderUnavailable",
    "ReplayCognitionProvider",
    "RuleCognitionInputs",
    "RuleCognitionProvider",
    "UnknownCognitionRequest",
    "UnrepresentableRuleResult",
    "build_messages",
    "build_repair_messages",
    "cognition_json_schema",
    "prompt_template_sha256",
    "resolve_api_key",
    "rule_cognition_result",
    "rule_emotion",
]
